name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make

    - name: make run
      run: make run 
    
    - name: make tests
      run: make tests

    # - name: make valgrind
    #   if: matrix.os == 'ubuntu-20.04'
    #   run: |
    #     sudo apt install valgrind
    #     make valgrind CFLAGS=-fPIC
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: compiled-${{ matrix.os }}
        path: .
